options:
  logging: NONE

steps:
  # Step 1: Build and push Docker images for each microservice
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'src/adservice'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/adservice:$(date +%Y%m%d%H%M%S)'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'src/adservice'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/adservice:$(date +%Y%m%d%H%M%S)'

  # Repeat for other microservices
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'src/cartservice'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/cartservice:$(date +%Y%m%d%H%M%S)'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'src/cartservice'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/cartservice:$(date +%Y%m%d%H%M%S)'

  # Step 2: Update Kubernetes manifests with new image tags
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i -e "s|image: $_REGION-docker.pkg.dev/.*/adservice:.*|image: $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/adservice:$(date +%Y%m%d%H%M%S)|" kubernetes-manifests/adservice-deployment.yaml
        sed -i -e "s|image: $_REGION-docker.pkg.dev/.*/cartservice:.*|image: $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/cartservice:$(date +%Y%m%d%H%M%S)|" kubernetes-manifests/cartservice-deployment.yaml

  # Step 3: Apply updated Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes-manifests'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'
      - 'CLOUDSDK_COMPUTE_ZONE=$_REGION'

# Define the required substitutions (replace with actual values)
substitutions:
  _REGION: 'us-central1'
  _REPO: 'my-docker-repo'

# Specify artifacts to store the updated YAML files (optional)
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-cloudbuild-artifacts/'
    paths:
      - 'kubernetes-manifests/*'
