steps:
# Clean workspace (optional - uncomment if needed)
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['system', 'prune', '-a', '-f']

# Build and push all microservices
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-adservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/adservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/adservice/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-cartservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/cartservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/cartservice/Dockerfile',
    '.'
  ]
  timeout: '1800s'  # Increased timeout for cartservice

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-checkoutservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/checkoutservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/checkoutservice/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-currencyservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/currencyservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/currencyservice/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-emailservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/emailservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/emailservice/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-frontend'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/frontend/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-loadgenerator'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/loadgenerator:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/loadgenerator/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-paymentservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/paymentservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/paymentservice/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-productcatalogservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/productcatalogservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/productcatalogservice/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-recommendationservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/recommendationservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/recommendationservice/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-shippingservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/shippingservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/shippingservice/Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'build-shoppingassistantservice'
  args: [
    'build',
    '-t', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/shoppingassistantservice:latest',
    '--no-cache',
    '--build-arg', 'PROJECT_ID=$PROJECT_ID',
    '-f', 'src/shoppingassistantservice/Dockerfile',
    '.'
  ]

# Push all images to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-images'
  args: ['push', '--all-tags', '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/']

# Update Kubernetes manifests with new image tags
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'update-manifests'
  args:
  - prepare
  - --filename=kubernetes-manifests
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/adservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/cartservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/checkoutservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/currencyservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/emailservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/loadgenerator:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/paymentservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/productcatalogservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/recommendationservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/shippingservice:latest
  - --image=${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/shoppingassistantservice:latest
  - --output=output

substitutions:
  _ARTIFACT_REGISTRY_LOCATION: 'us-central1'  # change this to your desired location
  _REPOSITORY: 'my-docker-repo'               # updated to match your repository name
  _CLUSTER_NAME: 'my-cluster'                 # change this if enabling GKE deployment
  _CLUSTER_LOCATION: 'us-central1'            # change this if enabling GKE deployment

options:
  dynamic_substitutions: true
  logging: NONE
  machineType: 'N1_HIGHCPU_8'  # Added for more build resources

timeout: '3600s'  # Global timeout of 1 hour

images:
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/adservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/cartservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/checkoutservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/currencyservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/emailservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/loadgenerator:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/paymentservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/productcatalogservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/recommendationservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/shippingservice:latest'
- '${_ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/shoppingassistantservice:latest'
